package persistence.entities;
// Generated 03-feb-2017 21:29:15 by Hibernate Tools 4.3.1

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {


     private int idUsuario;
     private TipoUsuario tipousuario;
     private String nombre;
     private String password;
     private String hashedPassword;
     private String salt;
     private boolean activo;
	 private String nombreTipoUsuario;
    
    public Usuario() {		
    }

	
    public Usuario(int idUsuario, TipoUsuario tipousuario, boolean activo) {
        this.idUsuario = idUsuario;
        this.tipousuario = tipousuario;
        this.activo = activo;
		setNombreTipoUsuario();
    }
    public Usuario(int idUsuario, TipoUsuario tipousuario, String nombre, String password, boolean activo) {
       this.idUsuario = idUsuario;
       this.tipousuario = tipousuario;
       this.nombre = nombre;
       this.password = password;
       this.activo = activo;  
	   setNombreTipoUsuario();
    }
   
	// <editor-fold defaultstate="collapsed" desc="Getters and Setters"> 
	
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TipoUsuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(TipoUsuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public boolean isActivo() {
        return this.activo;
    }
    
    public void setActivo(boolean activo) {
        this.activo = activo;
    }
    
    public String getHashedPassword() {
        return hashedPassword;
    }

    public void setHashedPassword(String hashedPassword) {
        this.hashedPassword = hashedPassword;
    }

	public String getNombreTipoUsuario() {
		return tipousuario.getNombre();
	}

	public final void setNombreTipoUsuario() {
		this.nombreTipoUsuario = tipousuario.getNombre();
	}

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }
	
	// </editor-fold>	

}


